name: cloudy
description: "Your weather companion, come rain or shine."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.0.1
  diacritic: ^0.1.5
  dio: ^5.4.2+1
  flutter_bloc: ^8.1.5
  http: ^1.2.1
  json_annotation: ^4.8.1
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  redacted:
    path: ./packages/redacted-1.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  bloc_test: ^9.1.7
  mockito: ^5.4.4
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Cera
      fonts:
        - asset: assets/fonts/Cera-Pro-Thin-Demo.otf
          weight: 100
        - asset: assets/fonts/Cera-Pro-Light-Demo.otf
          weight: 300
        - asset: assets/fonts/Cera-Pro-Regular-Demo.otf
          weight: 400
        - asset: assets/fonts/Cera-Pro-Medium-Demo.otf
          weight: 500
        - asset: assets/fonts/Cera-Pro-Bold-Demo.otf
          weight: 700
        - asset: assets/fonts/Cera-Pro-Black-Demo.otf
          weight: 900